# Generated by Django 5.2.2 on 2025-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('from_field', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('jenis_data', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('accuracy', models.CharField(max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('deployment', models.CharField(max_length=100)),
            ],
        ),
    ]
