# Generated by Django 5.2.2 on 2025-06-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0002_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebutuhan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dataset', models.CharField(max_length=255)),
                ('jumlah_record', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('experience', models.TextField()),
                ('implementation', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_project', models.CharField(max_length=100)),
                ('final_model', models.CharField(max_length=100)),
                ('dokumentasi_link', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=100)),
                ('akurasi', models.FloatField()),
                ('metrics_tambahan', models.TextField()),
                ('status_acc', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
