# Generated by Django 5.2.2 on 2025-06-13 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0003_datasetrequest_datasetresponse_engineering_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('target', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('accuracy', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('features', models.TextField()),
                ('input', models.TextField()),
                ('process', models.TextField()),
                ('output', models.TextField()),
                ('algorithm', models.TextField()),
                ('activity', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
