# Generated by Django 5.2.2 on 2025-06-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu_creation', '0004_modelentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelentry',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='output',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelentry',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
