# Generated by Django 5.2.3 on 2025-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebutuhan', models.TextField()),
                ('deskripsi', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dataset', models.CharField(max_length=100)),
                ('jumlah_record', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EngineeringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectives', models.TextField()),
                ('experience', models.TextField()),
                ('implementation', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FinalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_project', models.CharField(max_length=50)),
                ('final_model', models.CharField(max_length=100)),
                ('dokumentasi_link', models.URLField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_model', models.CharField(max_length=100)),
                ('akurasi', models.FloatField()),
                ('metrics_tambahan', models.TextField()),
                ('status_acc', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
