# Generated by Django 5.2.3 on 2025-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_creation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasetrequest',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='datasetresponse',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='engineeringdata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='finalmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
